
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maivo
 */
public class Pascoa5 extends javax.swing.JFrame {

    /**
     * Creates new form Pascoa5
     */
    public Pascoa5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        sliTipo = new javax.swing.JSlider();
        sliPeso = new javax.swing.JSlider();
        sliPersonagem = new javax.swing.JSlider();
        sliBrinquedo = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        lblPersonagem = new javax.swing.JLabel();
        lblBrinquedo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("escolha o tipo de ovo [1]chocolate[2casca bombom[3]casca recheada");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPeso.setText("0");

        jLabel3.setText("diga o peso do ovo [1]300g,[2]400g,[3]500g,[4]700g[5]1000g");

        jLabel4.setText("categoria brinquedo:");

        lblTipo.setText("0");

        btnCalcular.setText("calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResultado.setText("o valor final e de :");

        sliTipo.setMaximum(3);
        sliTipo.setMinimum(1);
        sliTipo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliTipoStateChanged(evt);
            }
        });

        sliPeso.setMaximum(5);
        sliPeso.setMinimum(1);
        sliPeso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliPesoStateChanged(evt);
            }
        });

        sliPersonagem.setMaximum(4);
        sliPersonagem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliPersonagemStateChanged(evt);
            }
        });

        sliBrinquedo.setMaximum(3);
        sliBrinquedo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliBrinquedoStateChanged(evt);
            }
        });

        jLabel7.setText("categoria personagem");

        lblPersonagem.setText("0");

        lblBrinquedo.setText("0");

        jLabel10.setText("diga o tipo de ovo que voce quer [1]chocolate,[2]casca bombom[3]casca recheada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalcular)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBrinquedo)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(sliBrinquedo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sliPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblPersonagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(lblPeso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(sliPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(sliTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sliTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(sliPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sliBrinquedo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrinquedo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
    double total = 0;
    double x ;
    int tipo = sliTipo.getValue();
    int peso = sliPeso.getValue();
    int personagem = sliPersonagem.getValue();
    int brinquedo = sliBrinquedo.getValue();
    if (tipo == 1){
        total = total + 3;
    }
    if (peso==1){
        total = total + 10 + 3 ;
    }else if(peso==2){
        total = total + 15 + 4;
    }else if(peso==3){
        total = total +20 + 4.5;
    }else if(peso==4){
        total = total +30 +5 ;
    }else if(peso==5){
        total = total +45 + 5.5;
    }
    if (peso==1 && tipo==1){
        total = total  - 1; //subtrai 1 real ao ovo de 300 gramas com cascas
    }else if(peso==1 && tipo==2){
        total = total + 5;
    }else if(peso==2 && tipo==3){
        total = total +5;
    }else if(peso==3 && tipo==3){
        total = total + 10;
    }else if (peso==4&& tipo==3){
        total = total + 10;
    }else if (peso==5 && tipo==3){
        total = total + 5 ;
    }
    
    if (personagem==0){
        total=total+0;
    }else if(personagem==1){
        total = total + 5;
    }else if (personagem==2){
        total = total + 8;
        }else if (personagem==3){
        total = total + 13;
    }else if (personagem==4){
        total = total + 15 ;
    }
    
    if(brinquedo==0){
        total = total +0;
    }else if (brinquedo==1){
        total = total + 3;
    }else if (brinquedo==2){
        total = total + 8 ;
    }else if (brinquedo==3){
        total = total + 10;
    }
    total = total + 1.5 + 5;
    x = total * 0.18;
    total =total + x;
    DecimalFormat formatado = new DecimalFormat("0.00");    
    String valorFormatado = formatado.format(total);

    lblResultado.setText("o valor final e de R$"+valorFormatado);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void sliTipoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliTipoStateChanged
        // TODO add your handling code here:
        lblTipo.setText(Integer.toString(sliTipo.getValue()));
    }//GEN-LAST:event_sliTipoStateChanged

    private void sliPesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliPesoStateChanged
        // TODO add your handling code here:
        lblPeso.setText(Integer.toString(sliPeso.getValue()));

    }//GEN-LAST:event_sliPesoStateChanged

    private void sliPersonagemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliPersonagemStateChanged
        // TODO add your handling code here:
        lblPersonagem.setText(Integer.toString(sliPersonagem.getValue()));

    }//GEN-LAST:event_sliPersonagemStateChanged

    private void sliBrinquedoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliBrinquedoStateChanged
        // TODO add your handling code here:
         lblBrinquedo.setText(Integer.toString(sliBrinquedo.getValue()));

    }//GEN-LAST:event_sliBrinquedoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pascoa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pascoa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pascoa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pascoa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pascoa5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBrinquedo;
    private javax.swing.JLabel lblPersonagem;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSlider sliBrinquedo;
    private javax.swing.JSlider sliPersonagem;
    private javax.swing.JSlider sliPeso;
    private javax.swing.JSlider sliTipo;
    // End of variables declaration//GEN-END:variables
}
